namespace MapleClaude.Net;

/// <summary>
/// Server→Client opcodes (Kinoko OutHeader.java values).
/// Values are cast to short when reading the first 2 bytes of a decrypted payload.
/// </summary>
public enum InHeader : short
{
    CheckPasswordResult       = 0,
    GuestIDLoginResult        = 1,
    AccountInfoResult         = 2,
    CheckUserLimitResult      = 3,
    ConfirmEULAResult         = 5,
    CheckPinCodeResult        = 6,
    ViewAllCharResult         = 8,
    WorldInformation          = 10,
    SelectWorldResult         = 11,
    SelectCharacterResult     = 12,
    CheckDuplicatedIDResult   = 13,
    CreateNewCharacterResult  = 14,
    DeleteCharacterResult     = 15,
    MigrateCommand            = 16,
    AliveReq                  = 17,
    EnableSPWResult           = 21,
    LatestConnectedWorld      = 24,
    CheckExtraCharInfoResult  = 26,
    CheckSPWResult            = 27,
    InventoryOperation        = 28,
    InventoryGrow             = 29,
    StatChanged               = 30,
    TemporaryStatSet          = 31,
    TemporaryStatReset        = 32,
    ChangeSkillRecordResult   = 35,
    GivePopularityResult      = 37,
    Message                   = 38,
    MemoResult                = 40,
    CharacterInfo             = 61,
    PartyResult               = 62,
    FriendResult              = 65,
    GuildResult               = 67,
    BroadcastMsg              = 71,
    NotifyLevelUp             = 109,
    NotifyJobChange           = 111,
    SetField                  = 141,
    SetCashShop               = 143,
    GroupMessage              = 150,
    Whisper                   = 151,
    QuickslotMappedInit       = 175,
    UserEnterField            = 179,
    UserLeaveField            = 180,
    UserChat                  = 181,
    UserMove                  = 210,
    UserMeleeAttack           = 211,
    UserMagicAttack           = 213,
    UserHit                   = 218,
    UserEmotion               = 219,
    UserEffectLocal           = 233,
    UserTeleport              = 234,
    UserQuestResult           = 242,
    UserHP                    = 227,
    MobEnterField             = 284,
    MobLeaveField             = 285,
    MobMove                   = 287,
    MobCtrlAck                = 288,
    MobDamaged                = 294,
    MobHPChange               = 296,
    NpcEnterField             = 311,
    NpcLeaveField             = 312,
    NpcMove                   = 314,
    DropEnterField            = 322,
    DropLeaveField            = 324,
    ScriptMessage             = 363,
    OpenShopDlg               = 364,
    ShopResult                = 365,
    TrunkResult               = 368,
    FuncKeyMappedInit         = 398,
    MigrateToCashShopResult   = 56,
    TransferChannel           = 138,
    CashShopQueryCashResult   = 383,
    CashShopCashItemResult    = 384,
    SkillCooltimeSet          = 276,
}
