namespace MapleClaude.Net;

/// <summary>
/// Client→Server opcodes (Kinoko InHeader.java values).
/// Pass to <see cref="OutPacket"/> constructor.
/// </summary>
public enum OutHeader : short
{
    CheckPassword             = 1,
    WorldInfoRequest          = 4,
    SelectWorld               = 5,
    CheckUserLimit            = 6,
    ViewAllChar               = 13,
    SelectCharacterByVAC      = 14,
    SelectCharacter           = 19,
    MigrateIn                 = 20,
    CheckDuplicatedID         = 21,
    CreateNewCharacter        = 22,
    DeleteCharacter           = 24,
    AliveAck                  = 25,
    CheckSPWRequest           = 29,
    UserTransferChannelRequest = 42,
    UserMigrateToCashShopRequest = 43,
    UserMove                  = 44,
    UserSitRequest            = 45,
    UserMeleeAttack           = 47,
    UserShootAttack           = 48,
    UserMagicAttack           = 49,
    UserHit                   = 52,
    UserChat                  = 54,
    UserEmotion               = 56,
    UserHP                    = 59,
    UserSelectNpc             = 63,
    UserScriptMessageAnswer   = 65,
    UserShopRequest           = 66,
    UserChangeSlotPositionRequest = 77,
    UserStatChangeItemUseRequest = 78,
    UserAbilityUpRequest      = 98,
    UserAbilityMassUpRequest  = 99,
    UserSkillUpRequest        = 102,
    UserSkillUseRequest       = 103,
    UserSkillCancelRequest    = 104,
    UserDropMoneyRequest      = 106,
    UserGivePopularityRequest = 107,
    UserPartyRequest          = 108,
    UserCharacterInfoRequest  = 109,
    UserQuestRequest          = 119,
    FuncKeyMappedModified     = 159,
    PartyRequest              = 145,
    GuildRequest              = 149,
    FriendRequest             = 153,
    MobMove                   = 227,
    MobDropPickUpRequest      = 229,
    DropPickUpRequest         = 246,
    CashShopChargeParamRequest = 273,
    CashShopQueryCashRequest  = 274,
    CashShopCashItemRequest   = 275,
    QuickslotKeyMappedModified = 216,
    UserPortalTeleportRequest = 113,
    UserTransferFieldRequest  = 41,
}
