namespace MapleClaude.Net.Packet;

/// <summary>
/// Client → Server opcodes for MapleStory v95 (locale 8, patch "1").
/// Values mirror upstream Kinoko's <c>kinoko/server/header/InHeader.java</c>.
/// Re-run <c>tools/gen-opcodes</c> after pulling Kinoko changes.
/// </summary>
public enum InHeader : short
{
    CheckPassword = 1,
    GuestIDLogin = 2,
    AccountInfoRequest = 3,
    WorldInfoRequest = 4,
    SelectWorld = 5,
    CheckUserLimit = 6,
    ConfirmEULA = 7,
    SetGender = 8,
    CheckPinCode = 9,
    UpdatePinCode = 10,
    WorldRequest = 11,
    LogoutWorld = 12,
    ViewAllChar = 13,
    SelectCharacterByVAC = 14,
    VACFlagSet = 15,
    CheckNameChangePossible = 16,
    RegisterNewCharacter = 17,
    CheckTransferWorldPossible = 18,
    SelectCharacter = 19,
    MigrateIn = 20,
    CheckDuplicatedID = 21,
    CreateNewCharacter = 22,
    CreateNewCharacterInCS = 23,
    DeleteCharacter = 24,
    AliveAck = 25,
    ExceptionLog = 26,
    SecurityPacket = 27,
    EnableSPWRequest = 28,
    CheckSPWRequest = 29,
    EnableSPWRequestByVAC = 30,
    CheckSPWRequestByVAC = 31,
    CheckOTPRequest = 32,
    CheckDeleteCharacterOTP = 33,
    CreateSecurityHandle = 34,
    SSOErrorLog = 35,
    ClientDumpLog = 36,
    CheckExtraCharInfo = 37,
    CreateNewCharacter_Ex = 38,
    UserTransferFieldRequest = 41,
    UserTransferChannelRequest = 42,
    UserMigrateToCashShopRequest = 43,
    UserMove = 44,
    UserSitRequest = 45,
    UserPortableChairSitRequest = 46,
    UserMeleeAttack = 47,
    UserShootAttack = 48,
    UserMagicAttack = 49,
    UserBodyAttack = 50,
    UserMovingShootAttackPrepare = 51,
    UserHit = 52,
    UserChat = 54,
    UserEmotion = 56,
    UserHP = 59,
    UserSelectNpc = 63,
    UserScriptMessageAnswer = 65,
    UserShopRequest = 66,
    UserGatherItemRequest = 75,
    UserSortItemRequest = 76,
    UserChangeSlotPositionRequest = 77,
    UserStatChangeItemUseRequest = 78,
    UserPortalScrollUseRequest = 92,
    UserAbilityUpRequest = 98,
    UserSkillUpRequest = 102,
    UserSkillUseRequest = 103,
    UserSkillCancelRequest = 104,
    UserSkillPrepareRequest = 105,
    UserDropMoneyRequest = 106,
    UserCharacterInfoRequest = 109,
    UserPortalScriptRequest = 112,
    UserPortalTeleportRequest = 113,
    UserMapTransferRequest = 114,
    UserQuestRequest = 119,
    GroupMessage = 140,
    Whisper = 141,
    PartyRequest = 145,
    GuildRequest = 149,
    FriendRequest = 153,
    MobMove = 227,
    MobApplyCtrl = 228,
    NpcMove = 241,
    DropPickUpRequest = 246,
}

/// <summary>
/// Server → Client opcodes for MapleStory v95.
/// Values mirror upstream Kinoko's <c>kinoko/server/header/OutHeader.java</c>.
/// </summary>
public enum OutHeader : short
{
    CheckPasswordResult = 0,
    GuestIDLoginResult = 1,
    AccountInfoResult = 2,
    CheckUserLimitResult = 3,
    SetAccountResult = 4,
    ConfirmEULAResult = 5,
    CheckPinCodeResult = 6,
    UpdatePinCodeResult = 7,
    ViewAllCharResult = 8,
    SelectCharacterByVACResult = 9,
    WorldInformation = 10,
    SelectWorldResult = 11,
    SelectCharacterResult = 12,
    CheckDuplicatedIDResult = 13,
    CreateNewCharacterResult = 14,
    DeleteCharacterResult = 15,
    MigrateCommand = 16,
    AliveReq = 17,
    AuthenCodeChanged = 18,
    AuthenMessage = 19,
    SecurityPacket = 20,
    EnableSPWResult = 21,
    DeleteCharacterOTPRequest = 22,
    CheckCrcResult = 23,
    LatestConnectedWorld = 24,
    RecommendWorldMessage = 25,
    CheckExtraCharInfoResult = 26,
    CheckSPWResult = 27,
    PartyResult = 62,
    FriendResult = 65,
    GuildResult = 67,
    InventoryOperation = 28,
    StatChanged = 30,
    TemporaryStatSet = 31,
    TemporaryStatReset = 32,
    ChangeSkillRecordResult = 35,
    SkillUseResult = 36,
    Message = 38,
    SetField = 141,
    SetITC = 142,
    SetCashShop = 143,
    GroupMessage = 150,
    Whisper = 151,
    UserEnterField = 179,
    UserLeaveField = 180,
    UserChat = 181,
    UserMove = 210,
    UserEffectRemote = 224,
    UserEffectLocal = 233,
    MobEnterField = 284,
    MobLeaveField = 285,
    MobChangeController = 286,
    MobMove = 287,
    MobCtrlAck = 288,
    MobDamaged = 294,
    NpcEnterField = 311,
    NpcLeaveField = 312,
    NpcMove = 314,
    DropEnterField = 322,
    DropLeaveField = 324,
    FuncKeyMappedInit = 398,
    PetConsumeItemInit = 399,
    PetConsumeMPItemInit = 400,
    QuickslotMappedInit = 175,
    FootHoldInfo = 176,
    Clock = 163,
    BroadcastMsg = 71,
    ScriptMessage = 363,
    OpenShopDlg = 364,
    ShopResult = 365,
}
